sudo: false
language: java
jdk:
  - oraclejdk8
# GitHub strips the wrapper jar file so we have to force its download during the build
install:
  #- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn install -q -DskipTests=true
script: mvn clean verify
